#! /bin/sh

# with serial its easier to read the logs

echo "MULLE_HOSTNAME=\"${MULLE_HOSTNAME}\"" 2>&1

mulle-sde -v craft --serial || exit 1

if [ -d test ]
then
   mulle-sde -v test craft --serial
   mulle-sde -v test run
fi
