#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x


###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###


run_mulle_testgen()
{
   log_fluff "####################################"
   log_fluff ${MULLE_TESTGEN} ${MULLE_TESTGEN_FLAGS} "$@"
   log_fluff "####################################"

   exekutor ${MULLE_TESTGEN} ${MULLE_TESTGEN_FLAGS} "$@"
}


test_print()
{
   local class_pointer="$1"
   local name="$2"
   local signature="$3"
   local expectfile="$4"

   local text
   local result

   [ ! -f "${expectfile}" ] && fail "\"${expectfile}\" is missing"

   if ! result="`run_mulle_testgen method "${class_pointer}" "${name}" "${signature}" "7" `"
   then
      fail "mulle-testgen errored out"
   fi

   local diffs

   diffs="`diff -w -B <(echo "${result}") "${expectfile}" `"
   if [ ! -z "${diffs}" ]
   then
      printf "%s\n" "${result}" >&2
      fail "Diffs to \"${expectfile}\": ${diffs}"
   fi
}


main()
{
   MULLE_TESTGEN_FLAGS="${MULLE_TESTGEN_FLAGS:-$*}"

   _options_mini_main "$@"

   test_print "NSArray" \
              "+arrayWithArray:" \
              "NSArray *,NSArray *,SEL,NSArray *" \
              ex1.txt

   log_verbose "zsh: $ZSH_VERSION"
   log_verbose "bash: $BASH_VERSION"
   log_verbose "MULLE_BASH_EXE_SHELL: $MULLE_BASH_EXE_SHELL"

   log_verbose "----- #1 PASSED -----"

   test_print "NSArray" \
              "-initWithArray:" \
              "NSArray *,NSArray *,SEL,NSArray *" \
              ex2.txt
   log_verbose "----- #2 PASSED -----"

   test_print "NSArray" \
              "-subarrayWithRange:options:" \
              "NSArray *,NSArray *,SEL,NSRange,unsigned int"  \
              ex3.txt

   log_verbose "----- #3 PASSED -----"

   log_info "----- ALL PASSED -----"
}


init()
{
   MULLE_TESTGEN="${MULLE_TESTGEN:-${PWD}/../../mulle-testgen}"
}


init "$@"
main "$@"

